version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    user: "0:0" # postgresql 컨테이너가 루트 사용자로 실행되도록 설정
    volumes:
      - ./airflow/postgresql-persistence:/bitnami/postgresql
    entrypoint: /bin/bash -c "chown -R 1001:1001 /bitnami/postgresql && /opt/bitnami/scripts/postgresql/entrypoint.sh /opt/bitnami/scripts/postgresql/run.sh"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    user: "0:0"  # Redis 컨테이너가 루트 사용자로 실행되도록 설정
    volumes:
      - ./airflow/redis-persistence:/bitnami/redis
    entrypoint: /bin/bash -c "chown -R 1001:1001 /bitnami/redis && exec /opt/bitnami/scripts/redis/entrypoint.sh /opt/bitnami/scripts/redis/run.sh"


  airflow-worker:
    image: bitnami/airflow-worker:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_PORT=5432
      - AIRFLOW_BROKER_URL=redis://redis:6379/0
      - AIRFLOW_RESULT_BACKEND=db+postgresql://bn_airflow:bitnami1@postgresql:5432/bitnami_airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_UID=1001  # UID 설정
    volumes:
      - ./airflow/airflow-dags:/opt/bitnami/airflow/dags
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/plugins:/opt/bitnami/airflow/plugins

  airflow-scheduler:
    image: bitnami/airflow-scheduler:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_PORT=5432
      - AIRFLOW_BROKER_URL=redis://redis:6379/0
      - AIRFLOW_RESULT_BACKEND=db+postgresql://bn_airflow:bitnami1@postgresql:5432/bitnami_airflow
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_UID=1001  # UID 설정
    volumes:
      - ./airflow/airflow-dags:/opt/bitnami/airflow/dags
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/plugins:/opt/bitnami/airflow/plugins

  airflow:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_PORT=5432
      - AIRFLOW_BROKER_URL=redis://redis:6379/0
      - AIRFLOW_RESULT_BACKEND=db+postgresql://bn_airflow:bitnami1@postgresql:5432/bitnami_airflow
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__WEBSERVER__AUTHENTICATE=True
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
      - AIRFLOW_UID=1001  # UID 설정
    ports:
      - '8080:8080'
    volumes:
      - ./airflow/airflow-dags:/opt/bitnami/airflow/dags
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/plugins:/opt/bitnami/airflow/plugins

  airflow-init:
    image: bitnami/airflow:latest
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_PORT=5432
      - AIRFLOW_USERNAME=user
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_EMAIL=user@example.com
      - AIRFLOW_UID=1001  # UID 설정
    entrypoint: /bin/bash -c "airflow db upgrade && airflow users create --username $${AIRFLOW_USERNAME} --password $${AIRFLOW_PASSWORD} --firstname Airflow --lastname Admin --role Admin --email $${AIRFLOW_EMAIL}"
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./airflow/airflow-dags:/opt/bitnami/airflow/dags
      - ./airflow/logs:/opt/bitnami/airflow/logs
      - ./airflow/plugins:/opt/bitnami/airflow/plugins
