name: Terraform

on:
  push:
    branches:
      - feature/tfapply # feature/tfapply 브랜치에 push 시 실행
      - feature/destroy # feature/destroy 브랜치에 push 시 실행

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production # 배포 환경 지정 (예: production, staging)

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: INFRA # Terraform 작업 디렉토리 설정

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: INFRA

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: INFRA

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: INFRA

      - name: Terraform Plan
        id: plan
        if: github.ref == 'refs/heads/feature/tfapply' && github.event_name == 'push'  # feature/tfapply 브랜치 push 시 plan 실행
        run: terraform plan -no-color -input=false
        working-directory: INFRA
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/feature/tfapply' && github.event_name == 'push'  # feature/tfapply 브랜치 push 시 apply 실행
        run: terraform apply -auto-approve -input=false
        working-directory: INFRA

      - name: Terraform Destroy
        id: destroy
        if: github.ref == 'refs/heads/feature/destroy' && github.event_name == 'push'  # feature/destroy 브랜치 push 시 destroy 실행
        run: terraform destroy -auto-approve -input=false
        working-directory: INFRA